before_install:
  - sudo apt-get install libssl-dev
before_script: bundle exec rake clean clobber compile
script: bundle exec rake test
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-18mode
    - rvm: rbx-19mode
branches:
  only:
    - as
    - emle-as
    - emle
    - upstream

